name = "pic-ui"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2023-12-12"
routes = [
  { pattern = "https://pic.example.com", zone_name = "example.com" }
]

r2_buckets = [
  { binding = "PIC_R2", bucket_name = "pic" }
]

d1_databases = [
  { binding = "PIC", database_name = "PIC", database_id = "xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx" }
]

[placement]
mode = "smart"